import "../styles/globals.css";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="bg-gradient-to-r from-cyan-500 to-blue-500 pl-20 pr-20 ">
        <Component {...pageProps} />
      </div>
      <Footer />
    </>
  );
}

export default MyApp;
